// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.11.4
// source: atest.proto

package model

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmptySvcClient is the client API for EmptySvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmptySvcClient interface {
	EmptyCall(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type emptySvcClient struct {
	cc grpc.ClientConnInterface
}

func NewEmptySvcClient(cc grpc.ClientConnInterface) EmptySvcClient {
	return &emptySvcClient{cc}
}

func (c *emptySvcClient) EmptyCall(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/model.EmptySvc/EmptyCall", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmptySvcServer is the server API for EmptySvc service.
// All implementations must embed UnimplementedEmptySvcServer
// for forward compatibility
type EmptySvcServer interface {
	EmptyCall(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedEmptySvcServer()
}

// UnimplementedEmptySvcServer must be embedded to have forward compatible implementations.
type UnimplementedEmptySvcServer struct {
}

func (UnimplementedEmptySvcServer) EmptyCall(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EmptyCall not implemented")
}
func (UnimplementedEmptySvcServer) mustEmbedUnimplementedEmptySvcServer() {}

// UnsafeEmptySvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmptySvcServer will
// result in compilation errors.
type UnsafeEmptySvcServer interface {
	mustEmbedUnimplementedEmptySvcServer()
}

func RegisterEmptySvcServer(s grpc.ServiceRegistrar, srv EmptySvcServer) {
	s.RegisterService(&EmptySvc_ServiceDesc, srv)
}

func _EmptySvc_EmptyCall_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmptySvcServer).EmptyCall(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/model.EmptySvc/EmptyCall",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmptySvcServer).EmptyCall(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// EmptySvc_ServiceDesc is the grpc.ServiceDesc for EmptySvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmptySvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "model.EmptySvc",
	HandlerType: (*EmptySvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EmptyCall",
			Handler:    _EmptySvc_EmptyCall_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "atest.proto",
}
