// Code generated by goctl. DO NOT EDIT!
// Source: atest.proto

package emptysvc

import (
	"context"

	"gozero-test/model"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Empty = model.Empty

	EmptySvc interface {
		EmptyCall(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultEmptySvc struct {
		cli zrpc.Client
	}
)

func NewEmptySvc(cli zrpc.Client) EmptySvc {
	return &defaultEmptySvc{
		cli: cli,
	}
}

func (m *defaultEmptySvc) EmptyCall(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	client := model.NewEmptySvcClient(m.cli.Conn())
	return client.EmptyCall(ctx, in, opts...)
}
